services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T18-02-00Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_REGION: "${MINIO_REGION}"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - nginxproxymanager_nginxproxymanager-app-1-network

volumes:
  minio_data:

networks:
  nginxproxymanager_nginxproxymanager-app-1-network:
    external: true
