services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: unless-stopped
    env_file: .env.local
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:9000/minio/health/ready"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 120s
    networks:
      - nginxproxymanager_nginxproxymanager-app-1-network

volumes:
  minio_data:

networks:
  nginxproxymanager_nginxproxymanager-app-1-network:
    external: true
